language:
  - cpp

dist: xenial

sudo: false

compiler:
  - gcc

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - cmake
      - g++-6

env:
  - MATRIX_EVAL="CC=gcc-6 && CXX=g++-6"

before_install:
  - readonly PARENT_DIR=$(pwd)
  - eval "${MATRIX_EVAL}"

script:
  - cd ${PARENT_DIR}
  - git submodule update --init --recursive
  - mkdir build
  - cd build
  - cmake \
  -DCMAKE_CXX_FLAGS=${CXX_FLAGS} \
  -DCMAKE_BUILD_TYPE=Release \
  -DPYTHON_EXECUTABLE=$(python-config --prefix)/bin/python3.5 \
  -DPYTHON_LIBRARY=$(python-config --prefix)/lib/libpython3.5m.so \
  -DPYTHON_INCLUDE_DIR=$(python-config --prefix)/include/python3.5m ..
  - make -j`nproc`

notifications:
  email: false
